### ISSUE TITLE
Unclear how to use this with babelify

### ISSUE THREAD

**Issue by fatso83** [JedWatson/babel-plugin-object-assign#1]
A lot of people use Babel in conjunction with Browserify, but neither documentation mentions anything about how to configure plugins in [Babelify](https://github.com/babel/babelify) when using Browserify. Could you add an example to the README?

```
    // Our app bundler
    var appBundler = browserify({
        entries: [options.src], // Only need initial file, browserify finds the rest
    }).transform(
        babelify.configure({
            plugins: ["object-assign"]
        })
    );
````
results in `ReferenceError: Unknown option: plugins while parsing file:`

**Comment by cmmartin** [comment]
I'm doing the same thing but getting...

````TypeError: Transformer object-assign is resolving to a different Babel version to what is doing the actual transformation...````

I seem to be successfully running the plugin, but facing a different issue

**Comment by cmmartin** [comment]
FYI you can just ```require('babelify/polyfill')``` in your browserify entry point and you'll get Object.assign and a lot more

**Comment by fatso83** [comment]
> and a lot more
Which is exactly why I am interested in this package in the first place :-) No need for WeakMaps polyfills bloating my build, when this is all I need.

**Comment by JedWatson** [comment]
@fatso83 reading through the babelify docs, the example you posted should work.

@cmmartin sounds like a babel version mismatch, I've just bumped the `babel-core` version and will try it out.

**Comment by JedWatson** [comment]
OK I can replicate the `ReferenceError` and get `Unknown plugin "object-assign" while parsing file`

@sebmck any chance you can lend a hand?

Steps to reproduce:

```
git clone https://github.com/jedwatson/react-select
cd react-select
npm install
gulp build
```

The plugin is specified in the `react-component-gulp-tasks` package that `react-select` uses, see https://github.com/JedWatson/react-component-gulp-tasks/blob/master/tasks/dist.js#L23-L25

**Comment by sebmck** [comment]
Try doing:

```javascript
// Our app bundler
var appBundler = browserify({
    entries: [options.src], // Only need initial file, browserify finds the rest
}).transform(
    babelify.configure({
        plugins: [require("babel-plugin-object-assign")]
    })
);
```

**Comment by JedWatson** [comment]
I'm closer.

For one thing, you can pass the plugin as a reference (i.e. `require('babel-plugin-object-assign')` to get past error 1, which leads to error 2.

Turns out when you include both `babelify` and `babel-plugin-object-assign` in your project, they both include `babel-core` in their `node_modules` folder. Which means you end up with two babel's and they're not friends.

The actual solution is to _also_ include `babel-core` in your project dependencies and hope they all resolve to the same version and you get no duplicates. _Then_ it works. I'll add some notes to the readme and pick up with @sebmck on how best to deal with this at a plugin packaging level.

**Comment by sebmck** [comment]
Yeah, this issue was bought up in babel/babel#1244. Mid-term solution until I work out something solid is to run `npm dedupe` or uninstalling `babelify` and `babel-core` and then reinstalling both again so they both resolve to the same `babel-core` version.
